### PR TITLE
Added optional cancellation token parameters

### LINKED ISSUE #88: Add CancellationToken support
It would be great to be able to cancel `IGraphQLHttpExecutor.ExecuteQuery` and also anything that calls into it.

This should be as "easy" as just adding (optional?) `CancellationToken` parameters everywhere, yet it's quite a large number of API to adjust. 🙂

### PR DESCRIPTION
**Pull request by bddckr**
Resolves #88.

### CODE REVIEW

**Comment by bddckr** [comment]
Any info on why the build failed? Do I have to target another branch perhaps?

**Comment by sahb1239** [comment]
I'm currently investigating why the build has failed. My latest own branch does also fail.

**Comment by sahb1239** [comment]
It looks great! Would you also update the file GraphQLHttpClientExtentions with Cancellationtokens?

**Comment by bddckr** [comment]
Done! I also rebased it onto latest develop and got rid of the merge conflicts.

**Comment by sahb1239** [comment]
Thanks for your pull request. It will be released with the next minor release.

**Pull request merged**
